### ISSUE TITLE
Typing too quickly breaks cursor position

### ISSUE THREAD

**Issue by NiXXeD** [NiXXeD/chatty#101]
Waiting on upstream: https://github.com/angular/angular/issues/6311

**Comment by NiXXeD** [comment]
Upstream updated, should be solved when we upgrade ng2.

**Comment by scaryroy** [comment]
Hi, do you mean it should be resolved with the next RC?

**Comment by zoechi** [comment]
I think this can be closed

**Comment by NiXXeD** [comment]
Fixed by updating to latest ng release.
