### ISSUE TITLE
Build / Dependencies: Update to latest Angular 2

### ISSUE THREAD

**Issue by NiXXeD** [NiXXeD/chatty#106]
Some pretty big breaking changes in beta6. Seems to break the build entirely.

**Comment by MarkPieszak** [comment]
This ever get fixed? Wonder what broke it so much...

**Comment by NiXXeD** [comment]
Not that the build itself breaks - ng2 made breaking changes to their project that caused impacts. From my quick look around, it didn't seem to be a big change to fix it, but I haven't had time yet.

**Comment by NiXXeD** [comment]
https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02

**Comment by NiXXeD** [comment]
Working on this here: https://github.com/NiXXeD/chatty/tree/ng2-latest
