### ISSUE TITLE
Intl polyfill currently broken in Safari

### ISSUE THREAD

**Issue by smathson** [NiXXeD/chatty#115]
Don't know if you plan on supporting Safari or not, but just ran into this trying to test something else. See https://github.com/angular/angular/issues/3333

Quick read makes it sound like the CDN is no longer sufficient and this should be included via an NPM dependency now?

**Comment by TimeDoctor** [comment]
this probably explains why I have only been seeing one random thread lately in safari

**Comment by NiXXeD** [comment]
There's already an open issue regarding Intl polyfill: #91.
