### ISSUE TITLE
Hotkeys - Browser Compatibility

### ISSUE THREAD

**Issue by mrazzino** [NiXXeD/chatty#98]
Text entry fields (username, password, root post, reply to post) only allows limited character entry (it seems random, if I slam my hands all over the keyboard maybe 1 out of 10 entries works). Can copy/paste text into each field. 
Firefox 38.5.0
Windows 7 SP1

**Comment by mrazzino** [comment]
also Java version 8 update 66, if that matters

**Comment by NiXXeD** [comment]
Not using java thankfully so that doesn't matter.

**Comment by NiXXeD** [comment]
Also impacts Chrome F5 button.

**Comment by NiXXeD** [comment]
For now, I've disabled the hotkeys entirely until we can figure this out.

**Comment by NiXXeD** [comment]
I believe this is fixed now with latest angular build, so I'm re-enabling hotkeys. Let me know if you still see issues.
